# Generated by Django 3.0.7 on 2020-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mpttcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
